# Generated by Django 5.2.6 on 2025-09-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farminputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temp', models.FloatField()),
                ('avg_water', models.FloatField()),
                ('avg_pesticide', models.FloatField()),
                ('pesticide_name', models.CharField(choices=[('TI', 'Tihan'), ('TH', 'Thunder')], max_length=2)),
                ('fertilizer_name', models.CharField(choices=[('Manure', 'poultry'), ('UR', 'Urea Fertilizer'), ('NPK15', 'NPK15-15-15'), ('NPK20', 'NPK20-10-10'), ('NPK10', 'NPK10-20-10')], max_length=7)),
                ('avg_fertilizer', models.FloatField()),
                ('seed_variety', models.CharField(choices=[('PL', 'Platinum'), ('CB', 'Cobra')], max_length=2)),
                ('daily_observation', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
