# Generated by Django 5.2.6 on 2025-09-30 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farminputs',
            options={'verbose_name': 'Farminputs', 'verbose_name_plural': 'Farminputs'},
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Lagos', 'Lagos'), ('Ondo', 'Ondo'), ('Ekiti', 'Ekiti'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Kwara', 'Kwara'), ('Kano', 'Kano'), ('Rivers', 'Rivers')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
