# Generated by Django 5.2.6 on 2025-10-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_farminputs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farminputs',
            name='avg_fertilizer',
        ),
        migrations.RemoveField(
            model_name='farminputs',
            name='avg_pesticide',
        ),
        migrations.RemoveField(
            model_name='farminputs',
            name='fertilizer_name',
        ),
        migrations.RemoveField(
            model_name='farminputs',
            name='pesticide_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='farminputs',
            name='cocopeat_name',
            field=models.CharField(blank=True, choices=[('CO', 'Coco-Coir'), ('CB', 'Coco-Bliss'), ('GP', 'Golden-Peat')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='farminputs',
            name='cocopeat_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='farminputs',
            name='plant_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='farminputs',
            name='plant_stage',
            field=models.CharField(blank=True, choices=[('1', 'Nursery'), ('2', 'Permanent-Space')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='children_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='current_salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='emp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='spouse_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='streetname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='streetno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farminputs',
            name='avg_temp',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farminputs',
            name='avg_water',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farminputs',
            name='seed_variety',
            field=models.CharField(choices=[('PL', 'Platinum'), ('CB', 'Cobra-26-f1')], max_length=2),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='state',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Ondo', 'Ondo'), ('Ekiti', 'Ekiti'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Kwara', 'Kwara'), ('Kano', 'Kano'), ('Rivers', 'Rivers')], max_length=20),
        ),
        migrations.CreateModel(
            name='Farminputtwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fungicide_name', models.CharField(blank=True, choices=[('MA', 'Macozeb'), ('FL', 'Flash-One'), ('SA', 'Saaf'), ('CH', 'Champ-DP'), ('CO', 'Controphyl'), ('FS', 'Five-Star'), ('RG', 'Ridomil-Gold'), ('CT', 'CDN-Thunda'), ('JM', 'Jumper')], max_length=2, null=True)),
                ('avg_fungicide', models.FloatField(blank=True, default=0, null=True)),
                ('insecticide_name', models.CharField(choices=[('LG', 'Laraforce-Gold'), ('TI', 'Tihan'), ('VA', 'Vanguish'), ('BE', 'Belt-Expert'), ('AM', 'Ampligo'), ('AL', 'Allakat'), ('IM', 'Imiforce'), ('DO', 'Dominator')], max_length=2)),
                ('avg_insecticide', models.FloatField(blank=True, default=0, null=True)),
                ('micronutrient_name', models.CharField(choices=[('AG', 'Agrovert20-20-20'), ('AV', 'Agrovert6-13-46'), ('YA', 'Yara-Vita15000'), ('SU', 'Super-Fruit-Setting'), ('TF', 'Tecamin-Flower'), ('AR', 'Agriful'), ('AP', 'Agriphyt'), ('AM', 'Agric-Max'), ('PN', 'Potassium-Nitrate-Multi-k'), ('CN', 'Calcium-Nitrate'), ('MS', 'Magnium-Sulphate')], max_length=2)),
                ('avg_micronutrient', models.FloatField(blank=True, default=0, null=True)),
                ('fertilizer_name', models.CharField(choices=[('Manure', 'poultry'), ('UR', 'Urea Fertilizer'), ('NPK15', 'NPK15-15-15'), ('NPK20', 'NPK20-10-10'), ('NPK10', 'NPK10-20-10'), ('SSP', 'SSP')], max_length=7)),
                ('avg_fertilizer', models.FloatField(blank=True, default=0, null=True)),
                ('FI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='app.farminputs')),
            ],
            options={
                'verbose_name': 'Farminputtwo',
                'verbose_name_plural': 'Farminputtwo',
            },
        ),
    ]
