# Generated by Django 5.2.6 on 2025-10-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_farminputs_avg_fertilizer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farminputs',
            options={'verbose_name': 'Farminput', 'verbose_name_plural': 'Farminput'},
        ),
        migrations.AddField(
            model_name='farminputs',
            name='plant_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
