# Generated by Django 5.2.6 on 2025-11-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_farminputs_options_farminputs_plant_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lastname',
        ),
    ]
