# Generated by Django 5.2.6 on 2025-11-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_staff_user_staff_image_staff_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single')], max_length=2, null=True),
        ),
    ]
