# Generated by Django 5.2.6 on 2025-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_staff_gender_alter_staff_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='plant_stage',
            field=models.CharField(blank=True, choices=[('N', 'Nursery'), ('P', 'Permanent-Space')], max_length=2, null=True),
        ),
    ]
