# Generated by Django 5.2.6 on 2025-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_farminputs_plant_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='plant_stage',
            field=models.CharField(blank=True, choices=[('1', 'Nursery'), ('2', 'Permanent-Space')], max_length=2, null=True),
        ),
    ]
