# Generated by Django 5.2.6 on 2025-11-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_farminputs_plant_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminputtwo',
            name='avg_herbicide',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='herbicide_name',
            field=models.CharField(choices=[('FU', 'Force-Up'), ('BF', 'Bara-Force'), ('WC', 'Weed-Crusher'), ('SL', 'Slasher')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
