# Generated by Django 5.2.6 on 2025-12-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_farminputtwo_avg_herbicide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFarmrecordupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=60, null=True)),
                ('rectified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.farminputs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RequestFarmrecordupdates',
                'verbose_name_plural': 'RequestFarmrecordupdates',
            },
        ),
    ]
