# Generated by Django 5.2.6 on 2025-12-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_requestfarmrecordupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfarmrecordupdates',
            name='record_id',
            field=models.IntegerField(),
        ),
    ]
