# Generated by Django 5.2.6 on 2025-12-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_requestfarmrecordupdates_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='children_no',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='spouse_no',
        ),
    ]
