# Generated by Django 5.2.6 on 2025-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_staff_children_no_remove_staff_spouse_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
