# Generated by Django 5.2.6 on 2025-12-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_staff_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='emp_role',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
