# Generated by Django 5.2.6 on 2025-12-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_staff_emp_role_staff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10, null=True),
        ),
    ]
