# Generated by Django 5.2.6 on 2025-12-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_staff_marital_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff',
            new_name='name',
        ),
    ]
