# Generated by Django 5.2.6 on 2025-12-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_staff_staff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='staff',
        ),
    ]
