# Generated by Django 5.2.6 on 2025-12-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_name_staff_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminputs',
            name='plant_choice',
            field=models.CharField(blank=True, choices=[('1', 'Tomatoes'), ('2', 'Bell_Pepper'), ('3', 'Habanero')], max_length=2, null=True),
        ),
    ]
