# Generated by Django 5.2.6 on 2025-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_farminputs_plant_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminputs',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Observation_Images'),
        ),
    ]
