# Generated by Django 5.2.6 on 2025-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_farminputs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='plant_choice',
            field=models.CharField(blank=True, choices=[('Tomatoes', 'Tomatoes'), ('Bell_Pepper', 'Bell_Pepper'), ('Habanero', 'Habanero')], max_length=12, null=True),
        ),
    ]
