# Generated by Django 5.2.6 on 2025-12-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_farminputs_plant_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='seed_variety',
            field=models.CharField(choices=[('PL', 'Platinum'), ('CB', 'Cobra-26-f1'), ('Bell_Pepper', 'Bell_Pepper')], max_length=12),
        ),
    ]
