# Generated by Django 5.2.6 on 2025-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_farminputs_seed_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='seed_variety',
            field=models.CharField(choices=[('PL', 'Platinum'), ('CB', 'Cobra-26-f1'), ('BP', 'Bell_Pepper')], max_length=12),
        ),
    ]
