# Generated by Django 5.2.6 on 2025-12-28 22:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_farminputs_seed_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Observation_Images', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Profile_Images', validators=[app.models.validate_image_size]),
        ),
    ]
