# Generated by Django 5.2.6 on 2025-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_farminputs_image_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='seed_variety',
            field=models.CharField(choices=[('PL', 'Platinum'), ('CB', 'Cobra-26-f1'), ('SM', 'SIMBAD'), ('NT', 'NIKITA'), ('OT', 'OTHERS')], max_length=12),
        ),
        migrations.AlterField(
            model_name='staff',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
