# Generated by Django 5.2.6 on 2025-12-30 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_farminputs_seed_variety_alter_staff_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
