# Generated by Django 5.2.6 on 2025-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_farminputs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
