# Generated by Django 5.2.6 on 2025-12-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_farminputs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminputs',
            name='seed_variety_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='farminputs',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
