# Generated by Django 5.2.6 on 2026-01-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_farminputs_seed_variety_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminputs',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
