# Generated by Django 5.2.6 on 2026-01-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_farminputs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfarmrecordupdates',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
