# Generated by Django 5.2.6 on 2026-01-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_requestfarmrecordupdates_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminputtwo',
            name='avg_fertilizer_other',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='avg_fungicide_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='avg_herbicide_other',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='avg_insecticide_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='avg_micronutrient_other',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farminputs',
            name='seed_variety',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Cobra-26-f1', 'Cobra-26-f1'), ('SIMBAD', 'SIMBAD'), ('NIKITA', 'NIKITA'), ('OT', 'OTHERS')], max_length=12),
        ),
    ]
