# Generated by Django 5.2.6 on 2026-01-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_farminputtwo_avg_fertilizer_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farminputtwo',
            old_name='avg_fungicide_other',
            new_name='fertilizer_other',
        ),
        migrations.RenameField(
            model_name='farminputtwo',
            old_name='avg_insecticide_other',
            new_name='fungicide_other',
        ),
        migrations.RemoveField(
            model_name='farminputtwo',
            name='avg_fertilizer_other',
        ),
        migrations.RemoveField(
            model_name='farminputtwo',
            name='avg_herbicide_other',
        ),
        migrations.RemoveField(
            model_name='farminputtwo',
            name='avg_micronutrient_other',
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='herbicide_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='insecticide_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farminputtwo',
            name='micronutrient_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
